language: python

python:
    - "2.7"

#install all deps
install:  "pip2.7 install -r requirements.txt"

sudo: required

#run tests
script:
    - sh build_db.sh
    - python server.py &
    - python test.py
    - pkill -f server.py
