export const REQUEST_BALANCE = 'REQUEST_BALANCE';
export const RECEIVE_BALANCE = 'RECEIVE_BALANCE';

export const RECEIVE_TRANSACTIONS = 'RECEIVE_TRANSACTIONS';
export const REQUEST_TRANSACTIONS = 'REQUEST_TRANSACTIONS';

export const PAY_TAX = 'PAY_TAX';
export const REQUEST_SPENDING = 'REQUEST_SPENDING';
export const RECEIVE_SPENDING = 'RECEIVE_SPENDING';

export const RECEIVE_ACCOUNT_BALANCE_GRAPH = 'RECEIVE_ACCOUNT_BALANCE_GRAPH';