export const REQUEST_BALANCE = 'REQUEST_BALANCE';
export const RECEIVE_BALANCE = 'RECEIVE_BALANCE';

export const RECEIVE_TRANSACTIONS = 'RECEIVE_TRANSACTIONS';
export const REQUEST_TRANSACTIONS = 'REQUEST_TRANSACTIONS';

export const PAY_TAX = 'PAY_TAX';